name: Build and Push Docker Image
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: ECR Login
      uses: docker/login-action@v3
      with: 
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export to Docker
      uses: docker/build-push-action@v6
      with:
        load: true
        tags: test

    - name: Test
      run: |
        docker run --rm test

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.REGISTRY }}:latest